version: '3.6'
services:
  trainer:
    image: 'dream_go/trainer:0.5.0'
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
      DB: localhost:5000
    network_mode: 'host'
    user: 1000:1000
    volumes:
      - ./trainer/models:/app/models

  worker:
    image: 'dream_go/worker:0.5.0'
    deploy:
      resources:
        limits:
          cpus: '12'
    environment:
      NVIDIA_VISIBLE_DEVICES: 1
      DB: localhost:5000
    network_mode: 'host'
