[package]
name = "dream_go"
version = "0.2.0"
authors = ["Karl Sundequist Blomdahl <karl.sundequist.blomdahl@gmail.com>"]
license = "Apache-2.0"
publish = false

[features]
default = []

# print (a lot) of debug info during neural network evaluation
trace-cuda = []

[profile.dev]
opt-level = 2
debug = true

[dependencies]
lazy_static = "0.2"
libc = "0.2"
ordered-float = "0.5"
rand = "0.3"
regex = "0.2"
