[package]
name = "dream_go"
version = "0.3.0"
authors = ["Karl Sundequist Blomdahl <karl.sundequist.blomdahl@gmail.com>"]
license = "Apache-2.0"
publish = false

[features]
default = []

# print (a lot) of debug info during neural network evaluation
trace-cuda = []

# whether to enable tensor-cores in the cuDNN routines
tensor-core = []

# dump all finished search tree's to stdout
trace-mcts = []

[profile.dev]
opt-level = 2
debug = true

[dependencies]
lazy_static = "0.2"
libc = "0.2"
ordered-float = "0.5"
rand = "0.3"
regex = "0.2"
