version: '3'
services:
  base:
    image: dream_go/base
    build:
      context: .
      dockerfile: Dockerfile.base

  train:
    image: dream_go/train
    build:
      context: .
      dockerfile: Dockerfile.train
      args:
        - GIT_REV
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./data:/app/data:cached
      - ./models:/app/models:delegated
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864

  worker:
    image: dream_go/worker
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        - GIT_REV
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./networks:/app/networks

  board:
    image: dream_go/board
    build:
      context: .
      dockerfile: Dockerfile.board
    environment:
      - NVIDIA_VISIBLE_DEVICES=none
    volumes:
      - ./models:/app/models
    network_mode: host
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
