[package]
name = "go"
version = "1.0.0"
authors = []
license = "Apache-2.0"
publish = false

[lib]
name = "go"
crate-type = ["cdylib", "lib"]

[dependencies]
lazy_static = {version = "1.1", features = ["nightly"]}
rand = "0.5"
regex = "1.0"
libc = "0.2"
