[package]
name = "go"
version = "1.0.0"
authors = []
license = "Apache-2.0"
publish = false

[lib]
name = "go"
crate-type = ["cdylib", "lib"]

[dependencies]
lazy_static = {version = "1.2", features = ["nightly"]}
memchr = "2.1"
rand = "0.6"
regex = "1.1"
libc = "0.2"
